name: CI

on:
  push:
    branches:
    - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate metadata
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.repository_owner }}/telegram-basic-bot
        tags: |
          type=raw,value=latest
          type=ref,event=tag
        flavor: |
          latest=true

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
